[package]
name = "rustot"
version = "0.3.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AWS IoT"
readme = "README.md"
keywords = ["iot", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/rustot"
edition = "2018"
documentation = "https://docs.rs/rustot"
exclude = ["/documentation"]


[lib]
name = "rustot"

[[example]]
name = "linux"
required-features = ["ota_mqtt_data", "log"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bitmaps = { version = "^3.1", default-features = false }
embedded-hal = "=1.0.0-alpha.4"
heapless = { version = "0.7.0", features = ["serde"] }
mqttrust = { version = "0.4.0" }
nb = "1"
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
serde_cbor = { version = "^0.11", default-features = false, optional = true }
serde-json-core = { version = "0.4.0" }
smlang = "0.4.0"
optional_struct = "0.2.0"

log = { version = "^0.4", default-features = false, optional = true }
defmt = { version = "^0.2", optional = true }

[dev-dependencies]
native-tls = { version = "^0.2" }
rust-crypto = "^0.2"
embedded-nal = "0.6.0"
embedded-time = "0.11.0"
dns-lookup = "1.0.3"
mqttrust_core = "0.4.0"
env_logger = "0.8.4"

[features]
default = ["ota_mqtt_data"]

ota_mqtt_data = ["serde_cbor"]
ota_http_data = []

defmt-impl = ["defmt", "mqttrust/defmt-impl", "heapless/defmt-impl"]

defmt-default = ["defmt-impl"]
defmt-trace = ["defmt-impl"]
defmt-debug = ["defmt-impl"]
defmt-info = ["defmt-impl"]
defmt-warn = ["defmt-impl"]
defmt-error = ["defmt-impl"]
